import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconGitMerge,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconAperture,
  IconShoppingCart,
  IconHelp,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconLayout,
} from "@tabler/icons";

import { uniqueId } from "lodash";
import { dataLocalStorage, getLocalStorage } from "src/helper/publicFunction";
import { RouterName } from "src/routes/RouterName";
let data = getLocalStorage(dataLocalStorage.privileges);

const Menuitems = [
  {
    id: uniqueId(),
    title: "Dashboards",
    icon: IconAperture,
    href: RouterName.home.home,
  },
  {
    id: uniqueId(),
    title: "Car Types",
    icon: IconAperture,
    href: RouterName.carTypes.carTypes,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Car Type List",
        href: RouterName.carTypes.carTypes,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Car Type",
        href: RouterName.carTypes.createCarTypes,
      },
    ],
  },

  {
    id: uniqueId(),
    title: "Cars",
    icon: IconAperture,
    href: RouterName.cars.cars,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Cars List",
        href: RouterName.cars.cars,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Car",
        href: RouterName.cars.createCars,
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Drivers",
    icon: IconAperture,
    href: RouterName.driver.driver,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Drivers List",
        href: RouterName.driver.driver,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Driver",
        href: RouterName.driver.createDrivers,
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Charity",
    icon: IconAperture,
    href: RouterName.charity.charity,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Charity List",
        href: RouterName.charity.charity,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Charity",
        href: RouterName.charity.createCharity,
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Preference Types",
    icon: IconAperture,
    href: RouterName.preference.preference,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Preference Types",
        href: RouterName.preference.preference,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Preference",
        href: RouterName.preference.createPreference,
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Client Loyalty",
    icon: IconAperture,
    href: RouterName.clientLoyalty.clientLoyalty,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Client Loyalty",
        href: RouterName.clientLoyalty.clientLoyalty,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Loyalty",
        href: RouterName.clientLoyalty.createClientLoyalty,
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Additional Charge",
    icon: IconAperture,
    href: RouterName.additionalCharge.additionalCharge,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "List Charges",
        href: RouterName.additionalCharge.additionalCharge,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Charges",
        href: RouterName.additionalCharge.createAdditionalCharge,
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Client",
    icon: IconAperture,
    href: RouterName.client.client,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Client Lists",
        href: RouterName.client.client,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Client",
        href: RouterName.client.createClient,
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Client Address",
    icon: IconAperture,
    href: RouterName.clientAddress.clientAddress,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Client Address Lists",
        href: RouterName.clientAddress.clientAddress,
      },
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Add Client Address",
        href: RouterName.clientAddress.createClientAddress,
      },
    ],
  },
  {
    id: uniqueId(),
    title: "Users",
    icon: IconAperture,
    href: RouterName.users.users,
  },
  {
    id: uniqueId(),
    title: "Flash Cards",
    icon: IconAperture,
    href: RouterName.flashcard.flashcard,
    children: [
      {
        id: uniqueId(),
        icon: IconAperture,
        title: "Flashcard Category",
        href: RouterName.flashcard.age_range,
      },
      {
        id: uniqueId(),
        title: "Flashcard Details",
        icon: IconAperture,
        href: RouterName.flashcard.flashcardDetails,
      },
    ], // Has submenu items
  },
  {
    id: uniqueId(),
    title: "Activities",
    icon: IconAperture,
    href: RouterName.activities.activities,
  },
  {
    id: uniqueId(),
    title: "Topics",
    icon: IconAperture,
    href: RouterName.topics.topics,
    children: [
      {
        id: uniqueId(),
        title: "Topics Subitem 1",
        icon: IconAperture,
        href: RouterName.settings.settings,
      },
      {
        id: uniqueId(),
        title: "Topics Subitem 2",
        icon: IconAperture,
        href: RouterName.settings.legal_information,
      },
    ], // Has submenu
  },
];

// const Menuitems = [
//   {
//     navlabel: true,
//     subheader: "Home",
//   },

//   data["13"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Dashboards",
//     icon: IconAperture,
//     href: RouterName.home.home,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["2"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Users",
//     icon: IconAperture,
//     href: RouterName.users.users,
//     chip: "",
//     chipColor: "secondary",
//   },

//   data["3"]?.access_read == 1 && {
//     navlabel: true,
//     subheader: "FLASHCARD",
//   },
//   // data["3"]?.access_read == 1 && {
//   //   id: uniqueId(),
//   //   title: "Categories",
//   //   icon: IconAperture,
//   //   href: RouterName.flashcard.flashcardcategory,
//   //   chip: "",
//   //   chipColor: "secondary",
//   // },
//   data["3"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Flash Cards",
//     icon: IconAperture,
//     href: RouterName.flashcard.flashcard,
//     chip: "",
//     chipColor: "secondary",
//   },

//   // data["4"]?.access_read == 1 && {
//   //   id: uniqueId(),
//   //   title: "Our team",
//   //   icon: IconAperture,
//   //   href: RouterName.landing_page.our_team,
//   //   chip: "",
//   //   chipColor: "secondary",
//   // },
//   data["7"]?.access_read == 1 && {
//     navlabel: true,
//     subheader: "Activities",
//   },
//   data["7"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Categories",
//     icon: IconAperture,
//     href: RouterName.activities.category,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["7"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Age Ranges",
//     icon: IconAperture,
//     href: RouterName.flashcard.age_range,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["7"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Anything else",
//     icon: IconAperture,
//     href: RouterName.flashcard.level_of_difficulty,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["7"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Activities",
//     icon: IconAperture,
//     href: RouterName.activities.activities,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["8"]?.access_read == 1 && {
//     navlabel: true,
//     subheader: "Topics",
//   },
//   data["8"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Topics",
//     icon: IconAperture,
//     href: RouterName.topics.topics,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     navlabel: true,
//     subheader: "Homepage",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "General Homepage",
//     icon: IconAperture,
//     href: RouterName.landing_page.GeneralHomePage,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Header",
//     icon: IconAperture,
//     href: RouterName.landing_page.slidershow,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Languages",
//     icon: IconAperture,
//     href: RouterName.landing_page.languages,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Our Story",
//     icon: IconAperture,
//     href: RouterName.landing_page.ourStory,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["6"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "How it works",
//     icon: IconAperture,
//     href: RouterName.how_it_work.how_it_work,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Testimonials",
//     icon: IconAperture,
//     href: RouterName.landing_page.testimonials,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Benefits",
//     icon: IconAperture,
//     href: RouterName.landing_page.app_benefits,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Funders",
//     icon: IconAperture,
//     href: RouterName.landing_page.our_client,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Maps",
//     icon: IconAperture,
//     href: RouterName.landing_page.maps,
//     chip: "",
//     chipColor: "secondary",
//   },
//   (data["4"]?.access_read == 1 ||
//     data["10"]?.access_read == 1 ||
//     data["9"]?.access_read == 1) && {
//     navlabel: true,
//     subheader: "Other pages",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Impact Numbers",
//     icon: IconAperture,
//     href: RouterName.landing_page.impacts,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Stats",
//     icon: IconAperture,
//     href: RouterName.landing_page.stats,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["4"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Press",
//     icon: IconAperture,
//     href: RouterName.landing_page.press_blog_news,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["9"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Contact Us",
//     icon: IconAperture,
//     href: RouterName.ContactAs.ContactAs,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["10"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "FAQs",
//     icon: IconAperture,
//     href: RouterName.faqs.faqs,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["1"]?.access_read == 1 && {
//     navlabel: true,
//     subheader: "ADMINS",
//   },
//   data["1"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Admins",
//     icon: IconLayout,
//     href: RouterName.admins.admins,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["1"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Privileges",
//     icon: IconLayout,
//     href: RouterName.admins.privileges,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["5"]?.access_read == 1 && {
//     navlabel: true,
//     subheader: "Settings",
//   },
//   data["5"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Settings",
//     icon: IconAperture,
//     href: RouterName.settings.settings,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["5"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Legal Information",
//     icon: IconAperture,
//     href: RouterName.settings.legal_information,
//     chip: "",
//     chipColor: "secondary",
//   },

//   data["11"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Tips",
//     icon: IconAperture,
//     href: RouterName.tips.tips,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["14"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Send Notifications",
//     icon: IconAperture,
//     href: RouterName.notification.notification,
//     chip: "",
//     chipColor: "secondary",
//   },
//   data["12"]?.access_read == 1 && {
//     id: uniqueId(),
//     title: "Admin Logs",
//     icon: IconAperture,
//     href: RouterName.admins_logs.admins_logs,
//     chip: "",
//     chipColor: "secondary",
//   },

// ];

export default Menuitems;
